name: Build

on:
  push:
    branches:
      - main
      - develop
      - "release/**"
      - "hotfix/**"
    tags:
      - "*"
    paths-ignore:
      - "README.md"
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022, ubuntu-22.04, macos-12 ]

    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      NUGET_SOURCE: "https://api.nuget.org/v3/index.json"

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4.1.1
      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow
      - uses: actions/setup-dotnet@v4.0.0
        with:
          # codecov needs 2.1, unittests needs 3.1, gitversion needs 5.0
          dotnet-version: |
            2.1
            5.0
            6.0
            7.0
            8.0
      - name: Cache Tools
        uses: actions/cache@v3.3.2
        with:
          path: tools
          key: ${{ runner.os }}-tools-${{ hashFiles('recipe.cake') }}
      - name: Build project
        uses: cake-build/cake-action@v1.4.1
        with:
          script-path: recipe.cake
          target: CI
          cake-version: 1.3.0
      - name: Upload Issues
        uses: actions/upload-artifact@v3.1.3
        with:
          if-no-files-found: warn
          name: ${{ matrix.os }} Issues
          path: |
            BuildArtifacts/report.html
            BuildArtifacts/**/coverlet/*.xml
      - name: Upload Packages
        uses: actions/upload-artifact@v3.1.3
        if: runner.os == 'Windows'
        with:
          if-no-files-found: warn
          name: package
          path: BuildArtifacts/Packages/**/*